### PR TITLE
Added rot13 example

### PR DESCRIPTION
**Pull request by M3L73D**
Simple [ROT13 cipher](https://en.wikipedia.org/wiki/ROT13) implementation.

Had to get around and compare each character with letters instead of simple `a >= 'a' && a <= 'z'`, so the implementation may not be the cleanest.

Might be worth adding comparison operators with dynamic labels that can be used multiple times in the code, what do you think?

### CODE REVIEW

**Comment by kammt** [comment]
> Might be worth adding comparison operators with dynamic labels that can be used multiple times in the code, what do you think?

I was thinking about implementing that, but until now I couldn't come up with a good syntax. 
An easy way would be `name:command`, but that's *too* easy for devs to remember. What could be done is restrict the name like most websites restrict their passwords. So a label name:
- must be at least 8 characters long
- must contain letters from a-z, A-Z, numbers from 0-9 and a special character (maybe out of !?$%&§"#)
- and.. must contain "yeet" somewhere in its name?

Any ideas from your side?

**Review by kammt — APPROVED** [review]
Ok thats *a lot* of jumping around 
But everything seems to work - nicely done!

**Comment by M3L73D** [comment]
I thought about something like this maybe:

```
with great eax, comes great 4 # if eax > 4
# some code here
understandable, have a great day # end if
# continue
```

which is converted to

```
cmp eax, 4
jle .LYeet0
# some code here
.LYeet0:
# continue
``` 

where `.LYeet0`, `.LYeet1`, ... are generated dynamically, so this statement can be used many times. This is basically a > operation, same goes for >= < <=.

Can be implemented differently, it's just an idea.

**Comment by M3L73D** [comment]
If that's too much, I think cmp with conditional jumps would work too, just need to add 'em.

**Pull request merged**
