### PR TITLE
Version bump to v1.4

### PR DESCRIPTION
**Pull request by kammt**
Changes in a nutshell:
- new command: `[function name]: whomst has summoned the almighty one` - call a function
- Martyrdom: Kills you first when you try to kill it (When sending SIGINT aka. Ctrl+C to a MemeASM program, it will first send SIGKILL to its parent, in most cases the shell)
- Support for multiple input files
- Code improved and made more readable

### CODE REVIEW

**Comment by xarantolus** [comment]
I'm a bit confused on how the function calling is supposed to work. Because this currently doesn't work:

```
I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun print
    what can I say except H
    what can I say except e
    what can I say except l
    what can I say except l
    what can I say except o
    what can I say except ,
    what can I say except space
    what can I say except W
    what can I say except o
    what can I say except r
    what can I say except l
    what can I say except d
    what can I say except !
    what can I say except \n

    right back at ya, buckaroo

I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun main
    print: whomst has summoned the almighty one

    I see this as an absolute win
```

When I compile it on Linux (WSL) using the latest commit from the develop branch:

    memeasm -o './main' 'multi_funcs.memeasm' && ./main

I get three errors:

```
multi_funcs.memeasm:20: error: command does not belong to any function
multi_funcs.memeasm:22: error: command does not belong to any function
multi_funcs.memeasm:0: error: unable to create an executable if no main-function was defined
```

**Comment by kammt** [comment]
> I'm a bit confused on how the function calling is supposed to work. Because this currently doesn't work:

Your code itself is correct, but it seems like the function parser had a stroke while going through your code.. I'll take a look at it, thanks!

> (WSL)

:monkaChrist:

**Comment by kammt** [comment]
> Ah this should be fine

~ Me, a few weeks ago, pushing non-working code

Locally your code example works now, the issue should:tm: be fixed :+1:

**Comment by xarantolus** [comment]
Yes, it seems to work now.

Two more things i just noticed: when compiling an empty file, the compiler crashes:

```
memeasm -o './main' 'empty.memeasm' && ./main
empty.memeasm:0: error: unable to create an executable if no main-function was defined
Floating point exception (core dumped)
```

Also sometimes randomly while compiling I get the following error:

```
{standard input}: Assembler messages:
{standard input}:96: Error: symbol `.LConfusedStonks_0' is already defined
gcc exited unexpectedly with exit code 256. If you did not expect this to happen, please report this issue at https://github.com/kammt/MemeAssembly/issues so that it can be fixed
```

Just compile e.g. the following code like 10 times and you'll see this error.

```
I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun print_hi
    what can I say except h
    what can I say except i
    what can I say except \n

    right back at ya, buckaroo


I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun main
    print_hi: whomst has summoned the almighty one

    I see this as an absolute win
```

**Comment by kammt** [comment]
> Also sometimes randomly while compiling I get the following error (I think it's because of having multiple functions):

Yes that was the culprit - that and a mistake of mine. The chosen index by `confused stonks` is normally the nth command of  of a file. Yet it was implemented as being the nth command of a function. Meaning that if you had two functions and the random index was 2, both functions would now have a confused stonks label at their third command.

FYI: I've now started working on SIMD and float-support, and depending on how far I get with it I'll include it in this release

**Pull request merged**
